## Numpy rutine

In [34]:
import numpy as np

### One-D array

**1. Create a 1-D array**

In [35]:
arr1 = np.array([1,2,3,4,3])
print arr1

[1 2 3 4 3]


In [36]:
arr2 = np.array([3,2,6, 8, 3], float)
print arr2

[ 3.  2.  6.  8.  3.]


**Slice 1-D array**

In [37]:
print arr1[:2]

[1 2]


In [38]:
print arr2[3:]

[ 8.  3.]


In [39]:
print arr1[1:4]

[2 3 4]


### Two-D array
**Create a 2-D array**

In [40]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print arr3

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Slice 2-D array**

In [41]:
arr3[:, 2]

array([3, 6, 9])

In [42]:
arr3[2][2]

9

In [43]:
arr3[2,2]

9

In [44]:
arr3[:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [45]:
arr3[[1,2], [1,2]]  ## check how it work

array([5, 9])

**Slice array with boolean index**

In [47]:
print (arr3==3)

[[False False  True]
 [False False False]
 [False False False]]


In [48]:
print arr3[arr3==3]

[3]


In [49]:
print(arr3 > 4)

[[False False False]
 [False  True  True]
 [ True  True  True]]


In [50]:
print arr3[arr3>4]

[5 6 7 8 9]


### Special array

In [53]:
arr4 = np.zeros(3)
print arr4

[ 0.  0.  0.]


In [56]:
arr4 = np.zeros([3,3])
print arr4

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [59]:
arr5 = np.eye(3)
arr5

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [61]:
arr5 = np.eye(4)
arr5

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Array indexing

In [62]:
arr5[2,3] = 8
arr5

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  8.],
       [ 0.,  0.,  0.,  1.]])

In [63]:
arr4[2] = 100
arr4

array([[   0.,    0.,    0.],
       [   0.,    0.,    0.],
       [ 100.,  100.,  100.]])

### Array transpose

In [68]:
arr = np.array([[1,2,3], [4,5,6]])
print arr

[[1 2 3]
 [4 5 6]]


In [69]:
np.transpose(arr)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [71]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Unique value of an array

In [82]:
x = np.array([1,1,12,2,3,3,4,4,4,5,6])
print x

[ 1  1 12  2  3  3  4  4  4  5  6]


In [83]:
x1 = np.unique(x)
print x1

[ 1  2  3  4  5  6 12]


In [84]:
x = np.array([[1,2,2], [3,3,4]])
print x

[[1 2 2]
 [3 3 4]]


In [85]:
x1 = np.unique(x)
print x1

[1 2 3 4]


### Array arithmetic operations

In [78]:
arr1 = np.array([1,2,3])
print arr1

[1 2 3]


In [79]:
arr2 = np.array([3,4,5])
arr2

array([3, 4, 5])

In [80]:
arr1 + arr2

array([4, 6, 8])

In [81]:
arr1 - arr2

array([-2, -2, -2])

### Array dot products

In [86]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [87]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [88]:
np.dot(a, b.T)

32

In [89]:
np.dot(a, b)

32

In [90]:
a.dot(b)

32

In [91]:
b.dot(a)

32

In [92]:
a = np.array([[1,2,3,4], [2,3,5,6], [4,2,3,0]])
a

array([[1, 2, 3, 4],
       [2, 3, 5, 6],
       [4, 2, 3, 0]])

In [94]:
b = np.array([[1,2], [3,0],[1,0], [10,1]])
b

array([[ 1,  2],
       [ 3,  0],
       [ 1,  0],
       [10,  1]])

In [95]:
np.dot(a,b)

array([[50,  6],
       [76, 10],
       [13,  8]])

In [97]:
a.dot(b)

array([[50,  6],
       [76, 10],
       [13,  8]])

**The column number of array a must equals the row number of array b**

### Histogram

In [104]:
s = np.array([2,2,4,5,6,7,3,3,1,3,2,5,7,8,4,5,5,6,8,3])
s

array([2, 2, 4, 5, 6, 7, 3, 3, 1, 3, 2, 5, 7, 8, 4, 5, 5, 6, 8, 3])

In [105]:
unique_s = np.unique(s)
print unique_s

[1 2 3 4 5 6 7 8]


In [106]:
n = unique_s.size
print n

8


In [107]:
frequence = np.zeros(n)
print frequence

[ 0.  0.  0.  0.  0.  0.  0.  0.]


In [108]:
for i in range(0,n):
    frequence[i] = np.sum(s==i+1)
print frequence

[ 1.  3.  4.  2.  4.  2.  2.  2.]


In [109]:
import matplotlib.pyplot as plt
%matplotlib inline